config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions

  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: :show
  resources :products, only: :show

  namespace :admin do
    root 'session#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, presence: { message: 'title must exist' }
  validates :title, uniqueness: { message: "名称不能重复" }

  has_ancestry orphan_strategy: :destroy

  has_many :products, dependent: :destroy

  def self.grouped_data
    self.roots.order(weight: :desc).inject([]) do |result, parent|
      row = []
      row << parent
      row << parent.children.order(weight: :desc)
      result << row
    end
  end

  before_validation :correct_ancestry
  private def correct_ancestry
    self.ancestry = nil if self.ancestry.blank?
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, -> { order(weight: 'desc') }, dependent: :destroy
  has_one :main_product_image, -> { order(weight: 'desc') },
    class_name: :ProductImage

  belongs_to :category

  before_create :set_default_attrs

  scope :onshelf, -> { where(status: Status::On) }

  validates :category_id, presence: { message: "分类不能为空" }
  validates :title, presence: { message: "名称不能为空" }
  validates :status, inclusion: { in: %w[on off],
    message: "商品状态必须为on | off" }
  validates :amount, numericality: { only_integer: true,
    message: "库存必须为整数" },
    if: proc { |product| !product.amount.blank? }
  validates :amount, presence: { message: "库存不能为空" }
  validates :msrp, presence: { message: "MSRP不能为空" }
  validates :msrp, numericality: { message: "MSRP必须为数字" },
    if: proc { |product| !product.msrp.blank? }
  validates :price, numericality: { message: "价格必须为数字" },
    if: proc { |product| !product.price.blank? }
  validates :price, presence: { message: "价格不能为空" }
  validates :description, presence: { message: "描述不能为空" }

  module Status
    On = 'on'
    Off = 'off'
  end

  private
  def set_default_attrs
    self.uuid = RandomCode.generate_product_uuid
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product

  has_attached_file :image, styles: {
    small: '60^x60',
    middle: '200^x200',
    big: "960x"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_size :image, in: 0..5.megabytes
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password, :password_confirmation

  validates_presence_of :email, message: '邮箱不能为空'
  validates_format_of :email, message: '邮箱格式不合法',
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
    if: proc { |user| user.email.present? }
  validates :email, uniqueness: true

  validates_presence_of :password, message: '密码不能为空',
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: '确认密码不能为空',
    if: :need_validate_password
  validates_confirmation_of :password
  validates_length_of :password, message: '密码最短为6位', minimum: 6,
    if: :need_validate_password

  def username
    self.email.split('@').first
  end

  private

  def need_validate_password
    self.new_record? ||
      (!self.password.nil? || !self.password_confirmation.nil?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected
  def fetch_home_data
    @categories = Category.grouped_data
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    fetch_home_data
    @category = Category.find(params[:id])
    @products = @category.products.onshelf.paginate(page: params[:page], per_page: 10)
      .order(id: :desc).includes(:main_product_image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    fetch_home_data
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = login(params[:email], params[:password])
      flash[:notice] = '登录成功！'
      redirect_to root_path
    else
      flash[:notice] = '邮箱或密码不正确！'
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    flash.notice = '退出成功'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = '注册成功！请登录'
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    fetch_home_data
    @products = Product.onshelf.paginate(page: params[:page], per_page: 10)
      .order(id: :desc).includes(:main_product_image)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= admin_categories_path %>">分类</a></li>
        <li><a href="<%= admin_products_path %>">商品</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>管理平台 - 蛋人商城</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'admin/layouts/menu' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>

      <%= yield %>
    </div>

    <%= javascript_include_tag 'admin' %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/layouts/_menu.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">ShoppingPlatform</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">分类</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="商品名称..">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">购物车</a></li>
        <% unless logged_in? %>
          <li><a href="<%= new_user_path %>">注册</a></li>
          <li><a href="<%= new_session_path %>">登录</a></li>
        <% else %>
        <li><a href="#">欢迎你, <%= current_user.username %></a></li>
        <li><%= link_to "退出", logout_path, method: :delete %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">我的订单</a></li>
            <li><a href="#">我的收获地址</a></li>
            <li><a href="#">我的收藏</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">个人信息</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingPlatform</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,
    maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'layouts/menu' %>

    <div class="container">
      <% unless flash.notice.blank? %>
        <div class="alert alert-info">
          <%= flash.notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts  %>
  </body>
</html>

app/views/shared/_categories.html.erb
<ul class="list-group">
  <% @categories.each do |group| %>
    <li class="list-group-item"><%= group.first.title %></li>
    <% group.last.each do |sub_category| %>
      <li class="list-group-item">
        <a href="<%= category_path(sub_category) %>">
          <%= sub_category.title %>
        </a>
      </li>
    <% end -%>
  <% end -%>
</ul>

app/views/shared/_products.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(product.main_product_image.image.url(:middle), alt: product.title), product_path(product) %>
        <div class="caption">
          <h4><%= link_to product.title, product_path(product), class: 'title' %></h4>
          <p><strong>¥<%= product.price %></strong> <span class="msrp">¥<%= product.msrp %></span></p>
          <p><a href="#" class="btn btn-danger btn-sm" role="button">加入购物车</a></p>
        </div>
      </div>
    </div>
  <% end -%>
</div>

<%= will_paginate @products %>